"""add server quote provenance to orders

Revision ID: 00cc6b950cf0
Revises: e604cdd3a0ef
Create Date: 2026-08-11 18:15:37.240708

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '00cc6b950cf0'
down_revision: str | Sequence[str] | None = 'e604cdd3a0ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reference_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('reference_price_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('reference_price_provider', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reference_price_provider')
    op.drop_column('orders', 'reference_price_timestamp')
    op.drop_column('orders', 'reference_price')
    # ### end Alembic commands ###