"""add version 1.2 trade proposals

Revision ID: 12389f5d58a5
Revises: a6eadd8735d9
Create Date: 2026-08-12 19:06:03.063745

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12389f5d58a5"
down_revision: str | Sequence[str] | None = "a6eadd8735d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("source_model_id", sa.UUID(), nullable=True),
        sa.Column("source_prediction_id", sa.UUID(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("proposed_notional", sa.Float(), nullable=False),
        sa.Column("allocation_fraction", sa.Float(), nullable=False),
        sa.Column("reference_price", sa.Float(), nullable=False),
        sa.Column("reference_price_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference_price_provider", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_proposals_account_id"), "trade_proposals", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_proposals_created_at"), "trade_proposals", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_trade_proposals_instrument_id"), "trade_proposals", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_proposals_order_id"), "trade_proposals", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_proposals_source_model_id"),
        "trade_proposals",
        ["source_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trade_proposals_source_prediction_id"),
        "trade_proposals",
        ["source_prediction_id"],
        unique=False,
    )
    op.create_index(op.f("ix_trade_proposals_status"), "trade_proposals", ["status"], unique=False)
    op.create_index(op.f("ix_trade_proposals_symbol"), "trade_proposals", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_proposals_symbol"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_status"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_source_prediction_id"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_source_model_id"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_order_id"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_instrument_id"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_created_at"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_account_id"), table_name="trade_proposals")
    op.drop_table("trade_proposals")
    # ### end Alembic commands ###
