"""add version 1 trading controls and execution audit

Revision ID: 1b61c26490b5
Revises: 00cc6b950cf0
Create Date: 2026-08-11 19:23:46.972441

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b61c26490b5"
down_revision: str | Sequence[str] | None = "00cc6b950cf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_controls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("control_key", sa.String(length=64), nullable=False),
        sa.Column("trading_enabled", sa.Boolean(), nullable=False),
        sa.Column("kill_switch_active", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_controls_control_key"), "trading_controls", ["control_key"], unique=True
    )
    op.create_table(
        "execution_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_audit_events_account_id"),
        "execution_audit_events",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_audit_events_created_at"),
        "execution_audit_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_audit_events_event_type"),
        "execution_audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_audit_events_order_id"),
        "execution_audit_events",
        ["order_id"],
        unique=False,
    )
    op.add_column("orders", sa.Column("client_order_id", sa.String(length=128), nullable=True))
    op.create_index(op.f("ix_orders_client_order_id"), "orders", ["client_order_id"], unique=False)
    op.create_unique_constraint(
        "uq_orders_account_client_order_id", "orders", ["account_id", "client_order_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_orders_account_client_order_id", "orders", type_="unique")
    op.drop_index(op.f("ix_orders_client_order_id"), table_name="orders")
    op.drop_column("orders", "client_order_id")
    op.drop_index(op.f("ix_execution_audit_events_order_id"), table_name="execution_audit_events")
    op.drop_index(op.f("ix_execution_audit_events_event_type"), table_name="execution_audit_events")
    op.drop_index(op.f("ix_execution_audit_events_created_at"), table_name="execution_audit_events")
    op.drop_index(op.f("ix_execution_audit_events_account_id"), table_name="execution_audit_events")
    op.drop_table("execution_audit_events")
    op.drop_index(op.f("ix_trading_controls_control_key"), table_name="trading_controls")
    op.drop_table("trading_controls")
    # ### end Alembic commands ###
