"""add version 1.4 strategy runs

Revision ID: 28ee8877afc5
Revises: 819b8bdee22d
Create Date: 2026-08-18 18:54:03.259614

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28ee8877afc5"
down_revision: str | Sequence[str] | None = "819b8bdee22d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("strategy_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("signal_count", sa.Integer(), nullable=False),
        sa.Column("proposal_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "strategy_key",
            "idempotency_key",
            name="uq_strategy_runs_account_strategy_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_strategy_runs_account_id"), "strategy_runs", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_runs_created_at"), "strategy_runs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_strategy_runs_status"), "strategy_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_strategy_runs_strategy_key"), "strategy_runs", ["strategy_key"], unique=False
    )
    op.create_table(
        "strategy_run_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_model_id", sa.UUID(), nullable=True),
        sa.Column("source_prediction_id", sa.UUID(), nullable=True),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["proposal_id"], ["trade_proposals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["strategy_run_id"], ["strategy_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "strategy_run_id", "sequence_number", name="uq_strategy_run_items_run_sequence"
        ),
    )
    op.create_index(
        op.f("ix_strategy_run_items_proposal_id"),
        "strategy_run_items",
        ["proposal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_run_items_status"), "strategy_run_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_run_items_strategy_run_id"),
        "strategy_run_items",
        ["strategy_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_run_items_symbol"), "strategy_run_items", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strategy_run_items_symbol"), table_name="strategy_run_items")
    op.drop_index(op.f("ix_strategy_run_items_strategy_run_id"), table_name="strategy_run_items")
    op.drop_index(op.f("ix_strategy_run_items_status"), table_name="strategy_run_items")
    op.drop_index(op.f("ix_strategy_run_items_proposal_id"), table_name="strategy_run_items")
    op.drop_table("strategy_run_items")
    op.drop_index(op.f("ix_strategy_runs_strategy_key"), table_name="strategy_runs")
    op.drop_index(op.f("ix_strategy_runs_status"), table_name="strategy_runs")
    op.drop_index(op.f("ix_strategy_runs_created_at"), table_name="strategy_runs")
    op.drop_index(op.f("ix_strategy_runs_account_id"), table_name="strategy_runs")
    op.drop_table("strategy_runs")
    # ### end Alembic commands ###
