"""add instruments and market bars

Revision ID: 455163c227ec
Revises:
Create Date: 2026-07-22 13:19:22.615466

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "455163c227ec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instruments_asset_class"), "instruments", ["asset_class"], unique=False
    )
    op.create_index(op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=True)
    op.create_table(
        "market_bars",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("high_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("low_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("volume", sa.Numeric(precision=30, scale=10), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id", "interval", "timestamp", "provider", name="uq_market_bars_identity"
        ),
    )
    op.create_index(
        op.f("ix_market_bars_instrument_id"), "market_bars", ["instrument_id"], unique=False
    )
    op.create_index(
        "ix_market_bars_instrument_interval_timestamp",
        "market_bars",
        ["instrument_id", "interval", "timestamp"],
        unique=False,
    )
    op.drop_index(op.f("ix_pipeline_run_pipeline_name"), table_name="pipeline_run")
    op.drop_index(op.f("ix_pipeline_run_status"), table_name="pipeline_run")
    op.drop_table("pipeline_run")
    op.drop_index(op.f("ix_audit_event_event_type"), table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("actor", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("resource_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(op.f("ix_audit_event_event_type"), "audit_event", ["event_type"], unique=False)
    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("pipeline_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("records_received", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("records_written", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("records_rejected", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("error_details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run")),
    )
    op.create_index(op.f("ix_pipeline_run_status"), "pipeline_run", ["status"], unique=False)
    op.create_index(
        op.f("ix_pipeline_run_pipeline_name"), "pipeline_run", ["pipeline_name"], unique=False
    )
    op.drop_index("ix_market_bars_instrument_interval_timestamp", table_name="market_bars")
    op.drop_index(op.f("ix_market_bars_instrument_id"), table_name="market_bars")
    op.drop_table("market_bars")
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_asset_class"), table_name="instruments")
    op.drop_table("instruments")
    # ### end Alembic commands ###
