"""add instruments and market bars

Revision ID: 88f2531b469d
Revises: a82da6a7064c
Create Date: 2026-07-22 13:32:09.654101

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "88f2531b469d"
down_revision: str | Sequence[str] | None = "a82da6a7064c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
