"""add model training tables

Revision ID: 98ca9ec30524
Revises: edb7cfd29506
Create Date: 2026-08-05 20:32:17.702937

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98ca9ec30524"
down_revision: str | Sequence[str] | None = "edb7cfd29506"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("model_type", sa.String(length=64), nullable=False),
        sa.Column("prediction_task", sa.String(length=32), nullable=False),
        sa.Column("target_column", sa.String(length=128), nullable=False),
        sa.Column("feature_columns", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("number_of_splits", sa.Integer(), nullable=False),
        sa.Column("test_size", sa.Integer(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_runs_dataset_id"), "training_runs", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_runs_mlflow_run_id"), "training_runs", ["mlflow_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_runs_model_type"), "training_runs", ["model_type"], unique=False
    )
    op.create_index(op.f("ix_training_runs_status"), "training_runs", ["status"], unique=False)
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("training_run_id", sa.UUID(), nullable=False),
        sa.Column("fold_number", sa.Integer(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("training_rows", sa.Integer(), nullable=False),
        sa.Column("validation_rows", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["training_run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_results_training_run_id"),
        "evaluation_results",
        ["training_run_id"],
        unique=False,
    )
    op.create_table(
        "model_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("training_run_id", sa.UUID(), nullable=False),
        sa.Column("model_type", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("artifact_uri", sa.Text(), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("feature_columns", sa.JSON(), nullable=False),
        sa.Column("target_column", sa.String(length=128), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["training_run_id"], ["training_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_artifacts_stage"), "model_artifacts", ["stage"], unique=False)
    op.create_index(
        op.f("ix_model_artifacts_training_run_id"),
        "model_artifacts",
        ["training_run_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_artifacts_training_run_id"), table_name="model_artifacts")
    op.drop_index(op.f("ix_model_artifacts_stage"), table_name="model_artifacts")
    op.drop_table("model_artifacts")
    op.drop_index(op.f("ix_evaluation_results_training_run_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_training_runs_status"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_model_type"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_mlflow_run_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_dataset_id"), table_name="training_runs")
    op.drop_table("training_runs")
    # ### end Alembic commands ###
