"""add version 1.6 strategy schedule worker leases

Revision ID: 9d520024e979
Revises: da83f6d2e623
Create Date: 2026-08-19 17:51:01.994437

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9d520024e979'
down_revision: str | Sequence[str] | None = 'da83f6d2e623'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_schedules', sa.Column('lease_owner', sa.String(length=128), nullable=True))
    op.add_column('strategy_schedules', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('strategy_schedules', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.add_column('strategy_schedules', sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('strategy_schedules', sa.Column('last_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_strategy_schedules_lease_expires_at'), 'strategy_schedules', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_lease_owner'), 'strategy_schedules', ['lease_owner'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_retry_at'), 'strategy_schedules', ['retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_schedules_retry_at'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_lease_owner'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_lease_expires_at'), table_name='strategy_schedules')
    op.drop_column('strategy_schedules', 'last_error')
    op.drop_column('strategy_schedules', 'retry_at')
    op.drop_column('strategy_schedules', 'failure_count')
    op.drop_column('strategy_schedules', 'lease_expires_at')
    op.drop_column('strategy_schedules', 'lease_owner')
    # ### end Alembic commands ###