"""add instruments and market bars

Revision ID: a82da6a7064c
Revises: 455163c227ec
Create Date: 2026-07-22 13:21:43.201733

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "a82da6a7064c"
down_revision: str | Sequence[str] | None = "455163c227ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
