"""create pipeline and audit tables

Revision ID: c7bde1fb8507
Revises: 
Create Date: 2026-07-21 19:09:28.300414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7bde1fb8507'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_event_type'), 'audit_event', ['event_type'], unique=False)
    op.create_table('pipeline_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_run'))
    )
    op.create_index(op.f('ix_pipeline_run_pipeline_name'), 'pipeline_run', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_pipeline_run_status'), 'pipeline_run', ['status'], unique=False)
    op.drop_table('dim_company')
    op.drop_table('fact_market_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_market_price',
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'trade_date', name=op.f('fact_market_price_pkey'))
    )
    op.create_table('dim_company',
    sa.Column('company_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cik', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('company_id', name=op.f('dim_company_pkey')),
    sa.UniqueConstraint('ticker', name=op.f('dim_company_ticker_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_pipeline_run_status'), table_name='pipeline_run')
    op.drop_index(op.f('ix_pipeline_run_pipeline_name'), table_name='pipeline_run')
    op.drop_table('pipeline_run')
    op.drop_index(op.f('ix_audit_event_event_type'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
