"""add version 1.5 strategy schedules

Revision ID: da83f6d2e623
Revises: 28ee8877afc5
Create Date: 2026-08-18 20:31:45.873176

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'da83f6d2e623'
down_revision: str | Sequence[str] | None = '28ee8877afc5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'strategy_key', 'name', name='uq_strategy_schedules_account_strategy_name')
    )
    op.create_index(op.f('ix_strategy_schedules_account_id'), 'strategy_schedules', ['account_id'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_enabled'), 'strategy_schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_frequency'), 'strategy_schedules', ['frequency'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_next_run_at'), 'strategy_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_strategy_schedules_strategy_key'), 'strategy_schedules', ['strategy_key'], unique=False)
    op.create_table('strategy_schedule_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['strategy_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_schedule_runs_created_at'), 'strategy_schedule_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_schedule_runs_schedule_id'), 'strategy_schedule_runs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_strategy_schedule_runs_status'), 'strategy_schedule_runs', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_schedule_runs_strategy_run_id'), 'strategy_schedule_runs', ['strategy_run_id'], unique=False)
    op.create_table('strategy_schedule_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_model_id', sa.UUID(), nullable=True),
    sa.Column('source_prediction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['strategy_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'sequence_number', name='uq_strategy_schedule_signals_schedule_sequence')
    )
    op.create_index(op.f('ix_strategy_schedule_signals_schedule_id'), 'strategy_schedule_signals', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_strategy_schedule_signals_symbol'), 'strategy_schedule_signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_schedule_signals_symbol'), table_name='strategy_schedule_signals')
    op.drop_index(op.f('ix_strategy_schedule_signals_schedule_id'), table_name='strategy_schedule_signals')
    op.drop_table('strategy_schedule_signals')
    op.drop_index(op.f('ix_strategy_schedule_runs_strategy_run_id'), table_name='strategy_schedule_runs')
    op.drop_index(op.f('ix_strategy_schedule_runs_status'), table_name='strategy_schedule_runs')
    op.drop_index(op.f('ix_strategy_schedule_runs_schedule_id'), table_name='strategy_schedule_runs')
    op.drop_index(op.f('ix_strategy_schedule_runs_created_at'), table_name='strategy_schedule_runs')
    op.drop_table('strategy_schedule_runs')
    op.drop_index(op.f('ix_strategy_schedules_strategy_key'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_next_run_at'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_frequency'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_enabled'), table_name='strategy_schedules')
    op.drop_index(op.f('ix_strategy_schedules_account_id'), table_name='strategy_schedules')
    op.drop_table('strategy_schedules')
    # ### end Alembic commands ###