"""add version 1.8 trading controls

Revision ID: e8023e1b191f
Revises: fb2ef23e6e20
Create Date: 2026-08-19 20:23:58.548179

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e8023e1b191f'
down_revision: str | Sequence[str] | None = 'fb2ef23e6e20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
        # V1.8 replaces the legacy singleton/global trading-control
    # representation with account-scoped trading controls.
    #
    # Existing V1.7 rows cannot be mapped safely to a specific
    # paper account because they contain no account identifier.
    # Remove those obsolete development-state rows before adding
    # the required account_id foreign key.
    op.execute("DELETE FROM trading_controls")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_controls', sa.Column('account_id', sa.UUID(), nullable=False))
    op.add_column('trading_controls', sa.Column('manual_halt', sa.Boolean(), nullable=False))
    op.add_column('trading_controls', sa.Column('manual_halt_reason', sa.Text(), nullable=True))
    op.add_column('trading_controls', sa.Column('circuit_breaker_tripped', sa.Boolean(), nullable=False))
    op.add_column('trading_controls', sa.Column('circuit_breaker_reason', sa.String(length=64), nullable=True))
    op.add_column('trading_controls', sa.Column('circuit_breaker_message', sa.Text(), nullable=True))
    op.add_column('trading_controls', sa.Column('circuit_breaker_tripped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trading_controls', sa.Column('day_start_date', sa.Date(), nullable=True))
    op.add_column('trading_controls', sa.Column('day_start_equity', sa.Float(), nullable=True))
    op.add_column('trading_controls', sa.Column('maximum_daily_loss_fraction', sa.Float(), nullable=False))
    op.add_column('trading_controls', sa.Column('maximum_gross_exposure_fraction', sa.Float(), nullable=False))
    op.add_column('trading_controls', sa.Column('maximum_symbol_fraction', sa.Float(), nullable=False))
    op.add_column('trading_controls', sa.Column('maximum_order_fraction', sa.Float(), nullable=False))
    op.add_column('trading_controls', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_trading_controls_control_key'), table_name='trading_controls')
    op.create_index(op.f('ix_trading_controls_account_id'), 'trading_controls', ['account_id'], unique=True)
    op.create_foreign_key(None, 'trading_controls', 'paper_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trading_controls', 'control_key')
    op.drop_column('trading_controls', 'reason')
    op.drop_column('trading_controls', 'kill_switch_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_controls', sa.Column('kill_switch_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('trading_controls', sa.Column('reason', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('trading_controls', sa.Column('control_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trading_controls', type_='foreignkey')
    op.drop_index(op.f('ix_trading_controls_account_id'), table_name='trading_controls')
    op.create_index(op.f('ix_trading_controls_control_key'), 'trading_controls', ['control_key'], unique=True)
    op.drop_column('trading_controls', 'created_at')
    op.drop_column('trading_controls', 'maximum_order_fraction')
    op.drop_column('trading_controls', 'maximum_symbol_fraction')
    op.drop_column('trading_controls', 'maximum_gross_exposure_fraction')
    op.drop_column('trading_controls', 'maximum_daily_loss_fraction')
    op.drop_column('trading_controls', 'day_start_equity')
    op.drop_column('trading_controls', 'day_start_date')
    op.drop_column('trading_controls', 'circuit_breaker_tripped_at')
    op.drop_column('trading_controls', 'circuit_breaker_message')
    op.drop_column('trading_controls', 'circuit_breaker_reason')
    op.drop_column('trading_controls', 'circuit_breaker_tripped')
    op.drop_column('trading_controls', 'manual_halt_reason')
    op.drop_column('trading_controls', 'manual_halt')
    op.drop_column('trading_controls', 'account_id')
    # ### end Alembic commands ###