"""add version 1.7 strategy scheduler workers

Revision ID: fb2ef23e6e20
Revises: 9d520024e979
Create Date: 2026-08-19 18:37:32.577992

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fb2ef23e6e20'
down_revision: str | Sequence[str] | None = '9d520024e979'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('successful_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_workers_last_heartbeat_at'), 'strategy_workers', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_strategy_workers_status'), 'strategy_workers', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_workers_worker_id'), 'strategy_workers', ['worker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_workers_worker_id'), table_name='strategy_workers')
    op.drop_index(op.f('ix_strategy_workers_status'), table_name='strategy_workers')
    op.drop_index(op.f('ix_strategy_workers_last_heartbeat_at'), table_name='strategy_workers')
    op.drop_table('strategy_workers')
    # ### end Alembic commands ###