from finai.application.services.v38_learning_factory import (
    parse_thresholds,
)
from finai.application.services.v40_learning_service import (
    V40LearningService,
)
from finai.core.config import (
    Settings,
)


def create_v40_learning_service(
    *,
    settings: Settings,
) -> V40LearningService:
    return V40LearningService(
        database_url=(
            settings.database_url
        ),
        artifact_directory=(
            settings
            .v40_learning_artifact_directory
        ),
        shadow_directory=(
            settings
            .v40_shadow_directory
        ),
        minimum_rows=(
            settings
            .v40_minimum_rows
        ),
        forward_horizon_bars=(
            settings
            .v40_forward_horizon_bars
        ),
        target_minimum_edge_bps=(
            settings
            .v40_target_minimum_edge_bps
        ),
        holdout_fraction=(
            settings
            .v40_holdout_fraction
        ),
        walk_forward_folds=(
            settings
            .v40_walk_forward_folds
        ),
        purge_rows=(
            settings
            .v40_purge_rows
        ),
        round_trip_cost_bps=(
            settings
            .v40_round_trip_cost_bps
        ),
        long_probability_thresholds=(
            parse_thresholds(
                settings
                .v40_long_probability_thresholds
            )
        ),
        short_probability_thresholds=(
            parse_thresholds(
                settings
                .v40_short_probability_thresholds
            )
        ),
        inner_calibration_fraction=(
            settings
            .v40_inner_calibration_fraction
        ),
        minimum_balanced_accuracy=(
            settings
            .v40_minimum_balanced_accuracy
        ),
        minimum_macro_f1=(
            settings
            .v40_minimum_macro_f1
        ),
        minimum_net_return=(
            settings
            .v40_minimum_net_return
        ),
        minimum_positive_fold_fraction=(
            settings
            .v40_minimum_positive_fold_fraction
        ),
        minimum_trades=(
            settings
            .v40_minimum_trades
        ),
        maximum_holdout_drawdown=(
            settings
            .v40_maximum_holdout_drawdown
        ),
        minimum_promotion_improvement=(
            settings
            .v40_minimum_promotion_improvement
        ),
        minimum_regime_rows=(
            settings
            .v40_minimum_regime_rows
        ),
        require_non_mock_data=True,
    )